services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: "mariadb" # todo
    container_name: "mariadb"
    ports:
      - "3306:3306"
    env_file: .env
    networks:
      - inception
    # volumes:
    #   - ./data/mysql:/var/lib/mysql
  nginx:
    build:
      context: ./requirements/nginx
    image: "nginx" # todo
    container_name: "nginx"
    ports:
      - "443:443"
    env_file: .env
    networks:
      - inception
    depends_on:
      - wordpress
  wordpress:
    build:
      context: ./requirements/wordpress
    image: "wordpress"
    container_name: "wordpress"
    ports:
      - "80:80"
      # - "9000:9000"
    env_file: .env
    networks:
      - inception
networks:
  inception:
    driver: bridge