services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: ".env"
    volumes:
      - .data/mariadb:/var/lib/mysql
    networks:
      - inception
    ports:
      - 3306:3306
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: ".env"
    volumes:
      - .data/wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - 9000:9000
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - .data/wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - 443:443
networks:
  inception:
