# todo: change volume link
services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: ".env"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    ports:
      - 3306:3306
    restart: on-failure
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: ".env"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
      - redis
    networks:
      - inception
    ports:
      - 9000:9000
    restart: on-failure
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - 443:443
    restart: on-failure
  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    env_file: ".env"
    volumes:
      - wordpress_data:/var/www
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - 21:21
      - 21000-21010:21000-21010
    restart: on-failure
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - 8080:8080
    restart: on-failure
  resume:
    build: ./requirements/bonus/resume
    image: resume
    container_name: resume
    networks:
      - inception
    ports:
      - 8000:8000
    restart: on-failure
  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    networks:
      - inception
    ports:
      - 6379:6379
    restart: on-failure
  typeform:
    build: ./requirements/bonus/typeform
    image: typeform
    container_name: typeform
    networks:
      - inception
    ports:
      - 8081:8081
    restart: on-failure
networks:
  inception:
volumes:
  wordpress_data:
  mariadb_data:
