# todo: add restart in case of failure
# todo: change volume link

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: ".env"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    ports:
      - 3306:3306
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: ".env"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - 9000:9000
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/html/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - 443:443
  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    env_file: ".env"
    volumes:
      - wordpress_data:/var/www
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - 21:21
      - 21000-21010:21000-21010
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - 8080:8080
networks:
  inception:
volumes:
  wordpress_data:
  mariadb_data:
