# depends_on:
#   - mariadb
services:
  mariadb:
    build: ./requirements/mariadb
    # image: "mariadb" # todo
    container_name: "mariadb"
    ports:
      - "3306:3306"
    env_file: .env
    networks:
      - inception
    # volumes:
    #   - ./data/mysql:/var/lib/mysql
  nginx:
    build: ./requirements/nginx
    # image: "nginx" # todo
    container_name: "nginx"
    ports:
      - "443:443"
    env_file: .env
    networks:
      - inception
networks:
  inception:
    driver: bridge