# env_file: .env
services:
  mariadb:
    # container_name: "mariadb"
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
  nginx:
    # container_name: "nginx"
    build: ./requirements/nginx
    ports:
      - "443:443"
    # depends_on:
    #   - mariadb
