# Generated by Django 5.1.1 on 2025-02-12 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_form_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('session', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.JSONField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.form')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.question')),
            ],
        ),
    ]
